### ISSUE TITLE
Shorter (un-)muted sounds

### ISSUE THREAD

**Issue by alangecker** [Daedalus3/freeswitch-german-soundfiles#1]
thank you for the german audio files! they will be included in the upcoming bigbluebutton-docker [release v2.2.31-2](https://github.com/alangecker/bigbluebutton-docker/pull/85) ;)

In the related issue there was an suggestion regarding the length of the (un-)muted sounds:

> There [...] seems to be a bit of an initial delay (~.5s) with the 'conf-unmuted.wav' file. Maybe @Daedalus3 can provide a shorter version such as:
>    "Mikrofon eingeschaltet" instead of "Ihr Mikrofon ist nun wieder aktiv"
 >   "Mikrofon stummgeschaltet" instead of "Ihr Mikrofon ist jetzt auf stumm"

**Comment by Daedalus3** [comment]
Thanks for the feedback -I shortened both files.
