### ISSUE TITLE
Datensatz mit männlicher Stimme

### ISSUE THREAD

**Issue by M-Stenzel** [Daedalus3/freeswitch-german-soundfiles#3]
Hallo Daedalus3,

danke für diese sehr tolle Idee. Das habe ich zum Anlass genommen, den Datensatz 1:1 auf eine männliche Stimme (synthetisch) zu übertragen. Die Dateien conf-entry_sound.wav und conf-exit_sound.wav werden nicht verwendet (von bigbluebutton), sind somit nicht dabei.
Die Dateien sind hier zu finden: [https://www.xy-space.de/owncloud/index.php/s/lDXdNeFBte9Mg9K](https://www.xy-space.de/owncloud/index.php/s/lDXdNeFBte9Mg9K)
Am Anfang jeder Datei ist eine 3 Sekunden Pause eingefügt, da ich gemerkt habe, dass ohne diese Pause der erste Teil der Nachricht abgeschnitten werden kann.
Die Übersetzung in's Deutsche ist makellos (Deine wie dann auch meine).

Grüße,

Martin.

**Comment by Daedalus3** [comment]
Hey Martin,

thanks for the work you put into this. I have to admit though, that for my taste the sound package sounds too synthetic. That's why I decided not to add it to my repo. I also can't reproduce the "missing pause issue".

**Comment by EkkiBrue** [comment]
Hallo Daedalus und Martin.

Was haltet ihr davon die beiden Samplessets in ein  Repository zu führen ? @M-Stenzel: Leider funktioniert dein Link nicht mehr ;( 

Habt ihr Infos, ob der von euch beschriebene Weg mit der aktuellsten BBB / Freeswitch Version läuft ? Wäre es nicht auch denkbar die Samples an das Freeswitch Projekt zu übergeben, so dass die erste Lokalisierungen mit in die Config übernehmen könnten ?

Liebe Grüße und Danke für euren Einsatz...
